movie_recommendation_system/mainpage/urls.py
from django.urls import path
from . import views

app_name='mainpage'
urlpatterns=[
    #/music/
    #path('',views.index,name='index'),
    path('result',views.result,name='result'),
    path('form',views.form,name='form'),
    path('store_data',views.store_data,name='store_data')

]

movie_recommendation_system/movie_recommendation_system/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('mainpage/', include('mainpage.urls')),
  
]

movie_recommendation_system/mainpage/models.py
from __future__ import unicode_literals

from djongo import models

class movielist(models.Model):
    movie_name = models.CharField(max_length = 200, null = True)
    thumbnail = models.CharField(max_length = 2000, null = True)
    imdb = models.CharField(max_length = 20, null = True)
    sypnosis=models.CharField(max_length = 2000, null = True)
            
    def __str__(self):
        return self.movie_name

movie_recommendation_system/mainpage/views.py
# Create your views here.
from django.shortcuts import render,get_object_or_404
import pymongo

import numpy as np
import math
import json
from multiprocessing import Process # To call two function together
#User id and movie id starts from 0

 #Dictionary of movie_id reated by the user and their ratings


p=[]
q=[]
full_matrix=[]


#To connect to remote database 
#myclient = pymongo.MongoClient("mongodb://localhost:27017/")
myclient = pymongo.MongoClient("mongodb://admin:pass1234@cluster0-shard-00-00-qhthx.mongodb.net:27017,cluster0-shard-00-01-qhthx.mongodb.net:27017,cluster0-shard-00-02-qhthx.mongodb.net:27017/test?ssl=true&replicaSet=Cluster0-shard-0&authSource=admin&retryWrites=true")
mydb=myclient['movie_data'] 
maintable = mydb["mainpage_movielist"]
all_movies=maintable.find()  # It extracts all the movies from the database and show them. It is kept so that the request is called once and hence speed up the process


all_computed_matrixx=mydb["mainpage_all_computed_matrix"]
all_computed_matrix=all_computed_matrixx.find()

full_matrix=all_computed_matrix
temp_dict=all_computed_matrix[2]
full_matrix=temp_dict['user_rating']
full_matrix=np.array(json.loads(full_matrix))

temp_dict=all_computed_matrix[3]
movie_movie=temp_dict['movie_movie']
movie_movie_matrix=np.array(json.loads(movie_movie))


input_from_the_user={}

def form(request):
    '''
    This function is called when user lands in the mainpage of the website
    It displays all the movies in the database and ask user to rate those movies.
    At least 5 movies 
    Returns -
    all_movies : All the movies that are present in the database
    user_entries : No. of movies that the user has to rate to activate the recommendation process
    '''
    global input_from_the_user
    input_from_the_user.clear()
    all_movies=maintable.find() 
    return render(request,"mainpage/main.html",{'all_movies':all_movies,'user_entries': 5 - len(input_from_the_user) })


def store_data(request):
    '''
    This function is called when user submits the rating. 
    It takes rating through post request and stores it in the dictionary variable named input_from_the_user
    Returns -
    all_movies : All the movies that are present in the database
    user_entries : No. of movies that the user has to rate to activate the recommendation process
    current_rating : Dictionary containing movies the user has rated so far and their respective ratings
    movies_user_have_chosen : List of id of movies that the user has rated so far
    '''
    global input_from_the_user
    input_from_the_user[int(request.POST.get('rating[post_id]'))]=int(request.POST.get('rating[rating]'))
    input_movie_id=list(input_from_the_user.keys())
    input_movie_id= list(map(int, input_movie_id))
    all_movies=maintable.find()
    #input_from_the_user = {int(k):int(v) for k,v in input_from_the_user.items()}
    return render(request,"mainpage/main.html",{'all_movies':all_movies,'user_entries':5-len(input_from_the_user),'current_rating': input_from_the_user ,'movies_user_have_chosen':input_movie_id } )




def result(request):
    '''
    This function is executed when user presses the recommend button.It find the ids of movies which 
    match the taste of user based on the rating given by the user
    Returns-
    all_movies : Recommended movies for that particular user
    '''
    
    list_of_recommended_movies=recommend_a_movie(input_from_the_user)
    #print(list_of_recommended_movies)
    #data = maintable.find_one({'id': 20})
    search_query=[]
    for i in list_of_recommended_movies:
        a={'id':i}
        search_query.append(a)

    all_new_movies=maintable.find({"$or":search_query})  
    print(list_of_recommended_movies)
    print(input_from_the_user)
    return render(request,"mainpage/result.html",{'all_movies':all_new_movies,'user_entries':len(input_from_the_user) })


def recommend_a_movie(input_from_the_user):
    '''
    This funtion is used to find the movie ids og the movie that the user could like based 
    on the recommendations filled by the user  
    Parameters-
    input_from_the_user - dictionary of the movies the user has rated and their respective ratings
    Returns-
    The list of movie ids that are most suited for the user
    '''
    list_of_rated_movies_by_new_user = list(input_from_the_user.keys())
    full_matrix2=np.transpose(full_matrix) 
    length=len(full_matrix2)
    i=0                     #To cahnge
    user_rating_matrix_of_selected_movies=[]
    full_matrix2=list(full_matrix2)
    while(i<length):        
        if(i in list_of_rated_movies_by_new_user):    #We need to iterate over movies so we work of the transposed matrix of user rating       
            user_rating_matrix_of_selected_movies.append(full_matrix2[i])
        i+=1    
    
    user_rating_matrix_of_selected_movies=np.transpose(user_rating_matrix_of_selected_movies) #This is the matrix of all the user ration for those movies which are rated by user   
    new_user_rating=list(input_from_the_user.values())

    simalirity_dict={}      #Recored simalirity of each user with respect to the new user 
    count=0                 #This is made to maintain the count of userid
    for i in user_rating_matrix_of_selected_movies:     #Iterationg over all the present users to find user user simalirity    
        simalirity=make_cosine_matrix(new_user_rating,i)
        simalirity_dict[str(count)]=simalirity
        count+=1

    potential_rating_of_new_user=most_similar_user(simalirity_dict,input_from_the_user) 
    #To sort dictionary on the bases of values
    
    
    
    return potential_rating_of_new_user







def make_cosine_matrix(a,b):
    '''
    This function takes in two list and find the cosine simalirity between both the list
    Parameters-
    a = First list to compute cosine simalirity
    b = Second list to compute cosine simalirity
    Returns-

    cosine_relation : Cosine simalirity between both the list

    '''  
    mat1=np.array(a)
    mat2=np.array(b)
    i=0
    numrator=0   
    while(i<len(a)):
        numrator+=mat1[i]*mat2[i]
        i+=1          
    denominator=math.sqrt(np.dot(mat1,mat1)*np.dot(mat2,mat2))
    cosine_relation=numrator/denominator   
    return cosine_relation


def item_item_filter(input_from_the_user):
    '''
    This function implements item-item filter.It uses the movie-movie relation matrix that is present in the database 
    and use it to find most similar movies to the movies the user has entered.  
    Returns-
    recommended_movie_ids - A list of movie ids that are recommende to the user
    '''
    
    global movie_movie_matrix # to do 
    movie_id_of_movie_user_has_rated=list(input_from_the_user.keys())
    rating_from_the_user=list(input_from_the_user.values())
    dict_of_recommended_movies={}
    i=0
    while(i<len(rating_from_the_user)):
        if(rating_from_the_user[i]>3): #Because we don't want to find movies similar to the movies used don't like.
            current_movie_row=movie_movie_matrix[movie_id_of_movie_user_has_rated[i]]
            j=0
            while(j<len(current_movie_row)):
                if(current_movie_row[j]>0.7): #If simalirity between movie is greater that 0.7 Then it gets gets stored by multiplying the rating the user gave
                    dict_of_recommended_movies[j]=j*rating_from_the_user[i]
                j+=1
        i+=1 

    #To sort the dictionary on the bases on their values               
    sorted_recomended_movies=dict(sorted(dict_of_recommended_movies.items(), key=lambda x: x[1],reverse=True))
    recommended_movie_ids=list(sorted_recomended_movies.keys())
    
    return recommended_movie_ids


def most_popular_movies():
    '''
    This function is used to get id of most popular movies in the database according to imdb
    Returns-
    A list of id of most popular movies
    '''
    a=[497, 496, 494, 492, 490, 485, 480, 465, 464, 458, 447, 443, 441, 439, 413, 412, 409, 406, 405, 388, 386, 377, 371, 354, 328, 313]
    return a


    
def most_similar_user(simalirity_dict,input_from_the_user):
    '''

    This functions computes the list of movies that will be suitable for user on the bases of simalirity dictionary
    and if the simalirity with any user is not found then it recommend the movie on the bases of item item filter
    Returns-
    The list of recommended movie ids 
        
    '''
    # To sort the dictionary
    sorted_dict=dict(sorted(simalirity_dict.items(), key=lambda x: x[1],reverse=True))
    list_of_all_the_simalirities=list(sorted_dict.values())

    if(list_of_all_the_simalirities[0]>=0.8):   # List is sorted in reverse fashion so first index will hold the largest value
        count=0
        for i in list_of_all_the_simalirities:
            #The list is sorted so i am going to exploit that feature for my benifit
            if i<0.8 :  #reason for this number
                return all_most_related_users(sorted_dict,count)
            count+=1
        return all_most_related_users(sorted_dict,count)   # If all greater than 0.8
    else:        
        #Item item filter goes here
        #It finds related movies(with rating>3) + top movies(keep some of them on the bases of imdb rating)
        
        list_of_recommended_movies_through_itemfilter=item_item_filter(input_from_the_user)
        list_of_most_popular_movies=most_popular_movies()
        try:
        	p1 = Process(target=run_gradient_decent(input_from_the_user))
        	p1.start()
        finally:
        	if(len(list_of_recommended_movies_through_itemfilter)<15):
        		list_of_recommended_movies=list_of_recommended_movies_through_itemfilter
                list_of_recommended_movies.extend(list_of_most_popular_movies[:(20-len(list_of_recommended_movies_through_itemfilter))])
            else:
                list_of_recommended_movies=list_of_recommended_movies_through_itemfilter[:15]
                list_of_recommended_movies.extend(list_of_most_popular_movies[:5])

movie_recommendation_system/mainpage/templates/mainpage/main.html
{% load staticfiles %} 
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Movie Recommendation System</title>
    <meta charset="utf-8">
    <meta name="format-detection" content="telephone=no"/>
    <script src="aa/3ts2ksMwXvKRuG480KNifJ2_JNM.js"></script><link rel="icon" href="images/favicon.ico" type="image/x-icon">
    <link rel="stylesheet" href="{% static "aa/grid.css" %}">
    <link rel="stylesheet" href="{% static "aa/style.css" %}">
    <link rel="stylesheet" href="{% static "aa/mailform.css" %}">
    <link rel="stylesheet" href="{% static "aa/search.css" %}">
    <link rel="stylesheet" href="{% static "aa/camera.css" %}">
    <link rel="stylesheet" href="{% static "aa/google-map.css" %}">
    <link rel="stylesheet" href="{% static "aa/owl-carousel.css" %}">
    <link rel="stylesheet" href="{% static "aa/animate.css" %}">
    <link href='//fonts.googleapis.com/css?family=Roboto:400,700,500,800,300,100' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="{% static "aa/font-awesome.css" %}">

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    
    <script src="{% static "aa/jquery.js" %}"></script>
    <script src="{% static "aa/jquery-migrate-1.2.1.js" %}"></script>

    <!--[if lt IE 9]>
    <html class="lt-ie9">
    <div style=' clear: both; text-align:center; position: relative;'>
        <a href="http://windows.microsoft.com/en-US/internet-explorer/..">
            <img src="images/ie8-panel/warning_bar_0000_us.jpg" border="0" height="42" width="820"
                 alt="You are using an outdated browser. For a faster, safer browsing experience, upgrade for free today."/>
        </a>
    </div>
    <script src="js/html5shiv.js"></script>
    <![endif]-->

    <script src="{% static 'aa/device.min.js' %}"></script>
</head>
<body>
<div class="page text-center">
    <!--========================================================
                              HEADER
    =========================================================-->
    <header>
        <div id="stuck_container" class="stuck_container">
            <div class="container ">
               
                <div class="brand">
                    <h1 class="brand_name">
                        <a href="./">Recommend Me </a>
                    </h1>
                </div>

                
                <!--  Navbar -->
                
                <!--END  Navbar -->
            </div>
        </div>
        <section class="bg-primary  well-xs">
            <div class="container">
                <div class="row">
                    <!-- Inline-list -->

                    
                    <!-- END Inline-list -->
                </div>
            </div>
        </section>
    </header>
    <!--========================================================
                              CONTENT
    =========================================================-->
    <main>

        <!-- Camera 
        <div class="camera_container text-center">
            <div id="camera" class="camera_wrap text-center">
                <div data-src="images/page-1_slide01.jpg">
                    <div class="camera_caption fadeIn ">

                        <blockquote class="quote text-shadow">
                            <h2>
                                <cite class=""> The SpongeBob Movie</cite>
                            </h2>
                            <p>
                                <q>
                                    «SpongeBob SquarePants takes leave from the town of Bikini Bottom
                                    in order to track down King Neptune's stolen crown.»
                                </q>
                            </p>
                        </blockquote>
                        <div class="btn-group">
                            <a href="#" class="btn btn-default btn-md ">
                                Learn more
                            </a>
                            <a href="#" class="btn btn-default btn-md">
                                watch trailer
                            </a>
                        </div>
                    </div>
                </div>
                <div data-src="images/page-1_slide02.jpg">
                    <div class="camera_caption fadeIn">

                        <blockquote class="quote text-shadow">
                            <h2>
                               <cite class=""> Mad Max</cite>
                            </h2>
                            <p>
                            <q>
                                «In a self-destructing world, a vengeful Australian policeman sets out
                                to stop a violent motorcycle gang»
                            </q>
                            </p>
                        </blockquote>
                        <div class="btn-group">
                            <a href="#" class="btn btn-default btn-md ">
                                Learn more
                            </a>
                            <a href="#" class="btn btn-default btn-md">
                             
                </div>
            </div>
        </div>
-->
        <!-- END Camera -->

        <!--  Watch your favorite movies online -->
        <section class=" well-md parallax bg-contrast" data-url="images/parallax1.png" data-speed="1" data-mobile="true" >
            <div class="container">
                <h2>
                    Let's find some good movies for you
                </h2>

            </div>
        </section>
        <!-- END Watch your favorite movies online -->

        <!--  More movies -->
        <section class="well-lg">
            <div class="container " style="width: 80%;height:2000px;overflow: auto">

                <style>
                form {
	width: 100px;
    align:center;
  }
  
 .button {
	border: 0;
	background: transparent;
	font-size: 1.5em;
	margin: 0;
	padding: 0;
	float: right;
    align:left;
	color: white;
  
  }
  .button2 {
	border: 0;
	background: transparent;
	font-size: 1.5em;
	margin: 0;
    align:center;
	padding: 0;
	float: right;
  	color: red;
  }
  
  button:hover,
  button:hover + button,
  button:hover + button + button,
  button:hover + button + button + button,
  button:hover + button + button + button + button {
	color: #ffed2d;
  }
</style>
                <div class="row flow-offset-2 ">
                {% for movie in all_movies  %}
                    <div class="col-md-3 col-sm-6 col-xs-12 wow fadeInDown"  style="width: 25%;height:100%;overflow: auto">
                        <div class="product">
                            <a href="#"> <img src="{{ movie.thumbnail }}" alt=" Image not available"/></a>

                            <div class="product__body">
                                <a class="fa fa-imdb icon-sm" href="{{ movie.imbd_link }}"><span class="value">{{ movie.imdb }}</span></a>
                            </div>
                        </div>
                            <h5>{{movie.movie_name}} {{movie.year}} </h5>
                            <h6>{{ movie.genre }}</h6>
                        <form action="{% url 'mainpage:store_data' %}" method="POST"  >
                        {% csrf_token %}
                        <input type="hidden"  name="rating[post_id]" value="{{movie.id}}">
                        {% if movie.id in movies_user_have_chosen %}
                            {% with movie_unique_id=movie.id %}
  
                            {% for key, value in current_rating.items %} 
                                {% if key == movie_unique_id %} 
                                    {% with rating_of_this_movie=value %}
                                        <div align="right">
                                        <button {% if  rating_of_this_movie == 5 %} class="button button2"  {% else %} class="button"  {% endif %} type="submit" name="rating[rating]" value="5">&#9733;</button>
                                        <button {% if  rating_of_this_movie > 3 %} class="button button2"   {% else %} class="button" {% endif %} type="submit" name="rating[rating]" value="4">&#9733;</button>
                                        <button {% if  rating_of_this_movie > 2 %} class="button button2"   {% else %} class="button" {% endif %} type="submit" name="rating[rating]" value="3">&#9733;</button>
                                        <button {% if  rating_of_this_movie > 1 %} class="button button2"   {% else %} class="button" {% endif %} type="submit" name="rating[rating]" value="2">&#9733;</button>
                                        <button {% if  rating_of_this_movie > 0 %} class="button button2"   {% else %} class="button" {% endif %}  type="submit" name="rating[rating]" value="1">&#9733;</button>
                                        </div>
      
                                    {% endwith %} 
       
                                {% endif %}
                            {% endfor %}
      
                            {% endwith %} 
                        {% else %}
                                    <button  class="button"   type="submit" name="rating[rating]" value="5">&#9733;</button>
                                    <button  class="button"  type="submit" name="rating[rating]" value="4">&#9733;</button>
                                    <button class="button"  type="submit" name="rating[rating]" value="3">&#9733;</button>
                                    <button  class="button"  type="submit" name="rating[rating]" value="2">&#9733;</button>
                                    <button class="button"   type="submit" name="rating[rating]" value="1">&#9733;</button>


                        {% endif %}

  
                            </form> 
                        
                    </div>
                {% endfor %}            
                    
                    
                    
                    
                </div>
                
            </div>
           

            {% if user_entries < 1 %}
               <a class="btn  btn-block btn-lg btn-success" href="{% url 'mainpage:result' %}"> <div class="btn btn-default btn-md offset-4">Recommend me something</div></a>
            {% else %}
                <div class="btn btn-default btn-md offset-4"> {{ user_entries }}  left</a></div>
            {% endif %}
                <div class="container well-sm">
                
                
                    
                    
                    
                    
            
                </div>
            </div>
        </section>
        <!-- END More movies -->

       

        
        

    </main>

   
    
</div>

<script src="aa/script.js"></script>
<!-- begin olark code -->
{% comment %} 
<script data-cfasync="false" type='text/javascript'>/*<![CDATA[*/window.olark||(function(c){var f=window,d=document,l=f.location.protocol=="https:"?"https:":"http:",z=c.name,r="load";var nt=function(){
    f[z]=function(){
        (a.s=a.s||[]).push(arguments)};var a=f[z]._={
    },q=c.methods.length;while(q--){(function(n){f[z][n]=function(){
        f[z]("call",n,arguments)}})(c.methods[q])}a.l=c.loader;a.i=nt;a.p={
        0:+new Date};a.P=function(u){
        a.p[u]=new Date-a.p[0]};function s(){
        a.P(r);f[z](r)}f.addEventListener?f.addEventListener(r,s,false):f.attachEvent("on"+r,s);var ld=function(){function p(hd){
        hd="head";return["<",hd,"></",hd,"><",i,' onl' + 'oad="var d=',g,";d.getElementsByTagName('head')[0].",j,"(d.",h,"('script')).",k,"='",l,"//",a.l,"'",'"',"></",i,">"].join("")}var i="body",m=d[i];if(!m){
        return setTimeout(ld,100)}a.P(1);var j="appendChild",h="createElement",k="src",n=d[h]("div"),v=n[j](d[h](z)),b=d[h]("iframe"),g="document",e="domain",o;n.style.display="none";m.insertBefore(n,m.firstChild).id=z;b.frameBorder="0";b.id=z+"-loader";if(/MSIE[ ]+6/.test(navigator.userAgent)){
        b.src="javascript:false"}b.allowTransparency="true";v[j](b);try{
        b.contentWindow[g].open()}catch(w){
        c[e]=d[e];o="javascript:var d="+g+".open();d.domain='"+d.domain+"';";b[k]=o+"void(0);"}try{
        var t=b.contentWindow[g];t.write(p());t.close()}catch(x){
        b[k]=o+'d.write("'+p().replace(/"/g,String.fromCharCode(92)+'"')+'");d.close();'}a.P(2)};ld()};nt()})({
    loader: "static.olark.com/jsclient/loader0.js",name:"olark",methods:["configure","extend","declare","identify"]});
/* custom configuration goes here (www.olark.com/documentation) */
olark.identify('7830-582-10-3714');/*]]>*/</script><noscript><a href="https://www.olark.com/site/7830-582-10-3714/contact" title="Contact us" target="_blank">Questions? Feedback?</a> powered by <a href="http://www.olark.com?welcome" title="Olark live chat software">Olark live chat software</a></noscript>
<!-- end olark code -->
 
<script type="text/javascript">
 var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-7078796-5']);
  _gaq.push(['_trackPageview']);
  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();</script>
  {% endcomment %}
</body><!-- Google Tag Manager --><noscript><iframe src="//www.googletagmanager.com/ns.html?id=GTM-P9FT69"height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript><script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start': new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src='//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);})(window,document,'script','dataLayer','GTM-P9FT69');</script><!-- End Google Tag Manager -->
</html>

movie_recommendation_system/mainpage/templates/mainpage/result.html
{% load staticfiles %} 

<!doctype html>
<html>
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Light Theme</title>
<link href="{% static 'css/simpleGridTemplate.css' %}" rel="stylesheet" type="text/css">
</head>
<body>
<!-- Main Container -->
<div class="container"> 
  <!-- Header -->
  <header class="header">
    <h4 class="logo">Here is some of the movie recomendation for you</h4>
  </header>
  <!-- Hero Section -->
  
  <!-- Stats Gallery Section -->
  

  {% for movie in all_movies  %}
     {% if  forloop.counter0|divisibleby:4 %}
        <div class="gallery">
     {% endif %} 
    
    <div class="thumbnail"> <a href="#"><img src="{{ movie.thumbnail }}" alt="" width="2000" class="cards"/></a>
      <h4>{{movie.movie_name}} {{ movie.year}}</h4>
      <p class="tag">{{ movie.genre }}</p>
      <p class="text_column">{{movie.sypnosis}}</p>
    </div>
   {% endfor %}
  </div>
  {% comment %} 
  <div class="gallery">
    <div class="thumbnail"> <a href="#"><img src="images/bkg_06.jpg" alt="" width="2000" class="cards"/></a>
      <h4>TITLE</h4>
      <p class="tag">HTML, CSS, JS, WordPress</p>
      <p class="text_column">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
    </div>
    <div class="thumbnail"> <a href="#"><img src="images/bkg_06.jpg" alt="" width="2000" class="cards"/></a>
      <h4>TITLE</h4>
      <p class="tag">HTML, CSS, JS, WordPress</p>
      <p class="text_column">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
    </div>
    <div class="thumbnail"> <a href="#"><img src="images/bkg_06.jpg" alt="" width="2000" class="cards"/></a>
      <h4>TITLE</h4>
      <p class="tag">HTML, CSS, JS, WordPress</p>
      <p class="text_column">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
    </div>
    <div class="thumbnail"> <a href="#"><img src="images/bkg_06.jpg" alt="" width="2000" class="cards"/></a>
      <h4>TITLE</h4>
      <p class="tag">HTML, CSS, JS, WordPress</p>
      <p class="text_column">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
    </div>
  </div>
   {% endcomment %}
  <!-- Footer Section -->
  
</div>
<!-- Main Container Ends -->
</body>
</html>